# Install necessary packages: jq (for parsing JSON) and AWS CLI (to fetch secrets)
packages:
  yum:
    jq: []          # jq is a command-line JSON processor
    aws-cli: []     # AWS CLI lets us call AWS services like Secrets Manager

commands:
  01_load_env_from_secrets_manager:
    command: |
      # Define the name of your secret in AWS Secrets Manager
      SECRET_NAME="yourhealthjournal/dev/database"

      # Define the AWS region where your secret is stored
      REGION="us-east-2"

      # Print a message to Elastic Beanstalk logs for debugging
      echo "Fetching secret: $SECRET_NAME from region: $REGION"

      # Fetch the secret's raw JSON string using AWS CLI
      SECRET_JSON=$(aws secretsmanager get-secret-value \
        --secret-id "$SECRET_NAME" \
        --region "$REGION" \
        --query SecretString \
        --output text)

      # Use jq to convert each key-value in the JSON into an export line
      # Example output:
      # export DB_USER=root
      # export DB_PASS=YourActualPassword
      echo "$SECRET_JSON" | jq -r 'to_entries[] | "export \(.key)=\(.value)"' >> /etc/profile.d/set_app_env.sh

      # Make the environment variable export script executable
      chmod +x /etc/profile.d/set_app_env.sh
